version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: Contrasenya
      POSTGRES_USER: LuisVallejo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
